export const UPDATE_USER_FORM_MODAL = 'UPDATE_USER_FORM_MODAL';
export const UPDATE_ROLE_FORM_MODAL = 'UPDATE_ROLE_FORM_MODAL';
export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';
export const UPDATE_ROLE_LIST = 'UPDATE_ROLE_LIST';
export const UPDATE_PERMISSION_LIST = 'UPDATE_PERMISSION_LIST';
export const UPDATE_PERMISSION_GROUP_LIST = 'UPDATE_PERMISSION_GROUP_LIST';