export const UPDATE_SECTION_FORM = 'UPDATE_SECTION_FORM';
export const UPDATE_TAG_FORM = 'UPDATE_TAG_FORM';
export const UPDATE_TAG_LIST = 'UPDATE_TAG_LIST';
export const UPDATE_IMAGE_FORM = 'UPDATE_IMAGE_FORM';
export const UPDATE_SECTIONS_LIST = 'UPDATE_SECTIONS_LIST';
export const UPDATE_BREAD_CRUMBS = 'UPDATE_BREAD_CRUMBS';
